"""add_multi_promotion_support

Revision ID: 805e2f7ba7ce
Revises: 14bfa498a5d8
Create Date: 2025-11-12 03:23:49.197731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '805e2f7ba7ce'
down_revision: Union[str, None] = '14bfa498a5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_historical_rankings_date', table_name='historical_rankings')
    op.drop_index('idx_historical_rankings_division', table_name='historical_rankings')
    op.drop_index('idx_historical_rankings_fighter', table_name='historical_rankings')
    op.drop_index('idx_historical_rankings_issue', table_name='historical_rankings')
    op.drop_table('historical_rankings')
    op.drop_index('ix_favorite_collections_user_id_created_at', table_name='favorite_collections')
    op.create_unique_constraint('uq_fighter_rankings_natural_key', 'fighter_rankings', ['fighter_id', 'division', 'rank_date', 'source'])
    op.add_column('fighters', sa.Column('sherdog_url', sa.String(length=255), nullable=True))
    op.add_column('fighters', sa.Column('primary_promotion', sa.String(length=50), nullable=True))
    op.add_column('fighters', sa.Column('all_promotions', sa.JSON(), nullable=True))
    op.add_column('fighters', sa.Column('total_fights', sa.Integer(), nullable=True))
    op.add_column('fighters', sa.Column('amateur_record', sa.String(length=50), nullable=True))
    op.drop_index('ix_fighters_birthplace_country_division', table_name='fighters')
    op.drop_index('ix_fighters_name_trgm', table_name='fighters', postgresql_using='gin')
    op.drop_index('ix_fighters_nickname_trgm', table_name='fighters', postgresql_using='gin')
    op.drop_index('ix_fighters_streak_composite', table_name='fighters')
    op.drop_index('ix_fighters_training_country_division', table_name='fighters')
    op.create_index(op.f('ix_fighters_primary_promotion'), 'fighters', ['primary_promotion'], unique=False)
    op.add_column('fights', sa.Column('opponent_sherdog_id', sa.Integer(), nullable=True))
    op.add_column('fights', sa.Column('event_sherdog_id', sa.Integer(), nullable=True))
    op.add_column('fights', sa.Column('promotion', sa.String(length=50), nullable=True))
    op.add_column('fights', sa.Column('method_details', sa.String(length=255), nullable=True))
    op.add_column('fights', sa.Column('is_amateur', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('fights', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('fights', sa.Column('referee', sa.String(length=100), nullable=True))
    op.drop_index('ix_fights_fighter_id_event_date', table_name='fights')
    op.drop_index('ix_fights_opponent_event_date', table_name='fights')
    op.drop_index('ix_fights_opponent_id_event_date', table_name='fights')
    op.create_index(op.f('ix_fights_event_sherdog_id'), 'fights', ['event_sherdog_id'], unique=False)
    op.create_index(op.f('ix_fights_opponent_sherdog_id'), 'fights', ['opponent_sherdog_id'], unique=False)
    op.create_index(op.f('ix_fights_promotion'), 'fights', ['promotion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fights_promotion'), table_name='fights')
    op.drop_index(op.f('ix_fights_opponent_sherdog_id'), table_name='fights')
    op.drop_index(op.f('ix_fights_event_sherdog_id'), table_name='fights')
    op.create_index('ix_fights_opponent_id_event_date', 'fights', ['opponent_id', 'event_date'], unique=False)
    op.create_index('ix_fights_opponent_event_date', 'fights', ['opponent_id', sa.text('event_date DESC NULLS LAST')], unique=False)
    op.create_index('ix_fights_fighter_id_event_date', 'fights', ['fighter_id', 'event_date'], unique=False)
    op.drop_column('fights', 'referee')
    op.drop_column('fights', 'location')
    op.drop_column('fights', 'is_amateur')
    op.drop_column('fights', 'method_details')
    op.drop_column('fights', 'promotion')
    op.drop_column('fights', 'event_sherdog_id')
    op.drop_column('fights', 'opponent_sherdog_id')
    op.drop_index(op.f('ix_fighters_primary_promotion'), table_name='fighters')
    op.create_index('ix_fighters_training_country_division', 'fighters', ['training_country', 'division'], unique=False)
    op.create_index('ix_fighters_streak_composite', 'fighters', ['current_streak_type', 'current_streak_count'], unique=False)
    op.create_index('ix_fighters_nickname_trgm', 'fighters', ['nickname'], unique=False, postgresql_using='gin')
    op.create_index('ix_fighters_name_trgm', 'fighters', ['name'], unique=False, postgresql_using='gin')
    op.create_index('ix_fighters_birthplace_country_division', 'fighters', ['birthplace_country', 'division'], unique=False)
    op.drop_column('fighters', 'amateur_record')
    op.drop_column('fighters', 'total_fights')
    op.drop_column('fighters', 'all_promotions')
    op.drop_column('fighters', 'primary_promotion')
    op.drop_column('fighters', 'sherdog_url')
    op.drop_constraint('uq_fighter_rankings_natural_key', 'fighter_rankings', type_='unique')
    op.create_index('ix_favorite_collections_user_id_created_at', 'favorite_collections', ['user_id', 'created_at'], unique=False)
    op.create_table('historical_rankings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('issue_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('division_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('division_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fighter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movement', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='historical_rankings_pkey'),
    sa.UniqueConstraint('issue_number', 'division_code', 'rank', name='unique_ranking')
    )
    op.create_index('idx_historical_rankings_issue', 'historical_rankings', ['issue_number'], unique=False)
    op.create_index('idx_historical_rankings_fighter', 'historical_rankings', ['fighter_name'], unique=False)
    op.create_index('idx_historical_rankings_division', 'historical_rankings', ['division_code'], unique=False)
    op.create_index('idx_historical_rankings_date', 'historical_rankings', [sa.text('issue_date DESC')], unique=False)
    # ### end Alembic commands ###
