import { format } from "date-fns";

import type { FightGraphMetadata } from "@/types/fight-graph";

export interface FightGraphInsightsProps {
  /** Metadata payload containing derived analytics for the graph. */
  metadata: FightGraphMetadata | null;
}

/**
 * Sidebar content area that surfaces the analytical metadata generated by
 * the backend. Values are rendered defensively because the insights block
 * is optional depending on the server configuration.
 */
export function FightGraphInsights({ metadata }: FightGraphInsightsProps) {
  const insights = metadata?.insights;
  const generatedAt = metadata?.generated_at;

  return (
    <aside className="flex flex-col gap-6 rounded-3xl border border-slate-800/60 bg-slate-950/60 p-6 text-slate-100 shadow-xl">
      <header className="space-y-1">
        <h2 className="text-sm font-semibold uppercase tracking-[0.4em] text-slate-400">
          Insights
        </h2>
        {generatedAt && (
          <p className="text-xs text-slate-400/80">
            Generated {format(new Date(generatedAt), "PPP p")}
          </p>
        )}
        {!generatedAt && (
          <p className="text-xs text-slate-400/80">
            Insights generated alongside the graph aggregation.
          </p>
        )}
      </header>

      {insights ? (
        <div className="space-y-6">
          <section className="rounded-2xl border border-slate-800/60 bg-slate-900/40 p-4">
            <h3 className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">
              Network Health
            </h3>
            <dl className="mt-3 space-y-2 text-sm text-slate-200">
              {typeof insights.network_density === "number" && (
                <div className="flex items-center justify-between rounded-xl bg-slate-950/60 px-3 py-2">
                  <dt className="uppercase tracking-[0.3em] text-xs text-slate-400">
                    Density
                  </dt>
                  <dd className="font-mono text-base">
                    {insights.network_density.toFixed(3)}
                  </dd>
                </div>
              )}
              {typeof insights.average_fights_per_fighter === "number" && (
                <div className="flex items-center justify-between rounded-xl bg-slate-950/60 px-3 py-2">
                  <dt className="uppercase tracking-[0.3em] text-xs text-slate-400">
                    Avg fights / fighter
                  </dt>
                  <dd className="font-mono text-base">
                    {insights.average_fights_per_fighter.toFixed(1)}
                  </dd>
                </div>
              )}
            </dl>
          </section>

          {insights.division_breakdown && insights.division_breakdown.length > 0 && (
            <section className="rounded-2xl border border-slate-800/60 bg-slate-900/40 p-4">
              <h3 className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">
                Division Breakdown
              </h3>
              <ul className="mt-3 space-y-2 text-sm text-slate-200">
                {insights.division_breakdown.map((entry) => (
                  <li
                    key={entry.division}
                    className="flex items-center justify-between rounded-xl bg-slate-950/60 px-3 py-2"
                  >
                    <span className="uppercase tracking-[0.3em] text-xs text-slate-400">
                      {entry.division}
                    </span>
                    <span className="font-mono text-base">
                      {entry.count} ({entry.percentage}%)
                    </span>
                  </li>
                ))}
              </ul>
            </section>
          )}

          {insights.top_fighters && insights.top_fighters.length > 0 && (
            <section className="rounded-2xl border border-slate-800/60 bg-slate-900/40 p-4">
              <h3 className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">
                Hubs
              </h3>
              <ul className="mt-3 space-y-2 text-sm text-slate-200">
                {insights.top_fighters.map((fighter) => (
                  <li
                    key={fighter.fighter_id}
                    className="flex items-center justify-between rounded-xl bg-slate-950/60 px-3 py-2"
                  >
                    <span className="flex flex-col text-xs uppercase tracking-[0.3em] text-slate-400">
                      <span className="text-sm font-semibold tracking-normal text-slate-100">
                        {fighter.name}
                      </span>
                      {fighter.division && <span>{fighter.division}</span>}
                    </span>
                    <span className="flex flex-col items-end font-mono text-base">
                      <span>{fighter.total_fights} fights</span>
                      <span className="text-xs uppercase tracking-[0.3em] text-slate-400">
                        degree {fighter.degree}
                      </span>
                    </span>
                  </li>
                ))}
              </ul>
            </section>
          )}

          {insights.busiest_rivalries && insights.busiest_rivalries.length > 0 && (
            <section className="rounded-2xl border border-slate-800/60 bg-slate-900/40 p-4">
              <h3 className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">
                Rivalries
              </h3>
              <ul className="mt-3 space-y-2 text-sm text-slate-200">
                {insights.busiest_rivalries.map((rivalry) => (
                  <li
                    key={`${rivalry.source}-${rivalry.target}`}
                    className="space-y-1 rounded-xl bg-slate-950/60 px-3 py-2"
                  >
                    <p className="text-sm font-semibold text-slate-100">
                      {rivalry.source_name ?? rivalry.source} vs {rivalry.target_name ?? rivalry.target}
                    </p>
                    <p className="text-xs uppercase tracking-[0.3em] text-slate-400">
                      {rivalry.fights} fights
                      {rivalry.last_event_name && ` • ${rivalry.last_event_name}`}
                      {rivalry.last_event_date &&
                        ` • ${format(new Date(rivalry.last_event_date), "PP")}`}
                    </p>
                  </li>
                ))}
              </ul>
            </section>
          )}
        </div>
      ) : (
        <p className="text-sm text-slate-400/80">
          Insights will populate automatically once the fight graph loads.
        </p>
      )}
    </aside>
  );
}
