#!/bin/bash
set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

TUNNEL_NAME="ufc-pokedex"
DOMAIN="wolfgangschoenberger.com"
FRONTEND_SUBDOMAIN="ufc.${DOMAIN}"
API_SUBDOMAIN="api.ufc.${DOMAIN}"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║         UFC Pokedex - Cloudflare Tunnel Setup              ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if cloudflared is installed
if ! command -v cloudflared &> /dev/null; then
    echo -e "${RED}✗ Error: cloudflared is not installed${NC}"
    echo -e "${YELLOW}Install it with: brew install cloudflared${NC}"
    exit 1
fi

echo -e "${GREEN}✓ cloudflared is installed${NC}"
echo ""

# Step 1: Login to Cloudflare (if not already logged in)
echo -e "${BLUE}Step 1: Authenticating with Cloudflare...${NC}"
if [ ! -f "$HOME/.cloudflared/cert.pem" ]; then
    echo -e "${YELLOW}Opening browser for Cloudflare authentication...${NC}"
    cloudflared tunnel login
    echo -e "${GREEN}✓ Authentication complete${NC}"
else
    echo -e "${GREEN}✓ Already authenticated${NC}"
fi
echo ""

# Step 2: Create tunnel (if it doesn't exist)
echo -e "${BLUE}Step 2: Creating tunnel '${TUNNEL_NAME}'...${NC}"
if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
    echo -e "${YELLOW}⚠ Tunnel '${TUNNEL_NAME}' already exists${NC}"
    TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "$TUNNEL_NAME" | awk '{print $1}')
    echo -e "${GREEN}✓ Using existing tunnel ID: ${TUNNEL_ID}${NC}"
else
    cloudflared tunnel create "$TUNNEL_NAME"
    TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "$TUNNEL_NAME" | awk '{print $1}')
    echo -e "${GREEN}✓ Tunnel created with ID: ${TUNNEL_ID}${NC}"
fi
echo ""

# Step 3: Create DNS routes
echo -e "${BLUE}Step 3: Creating DNS routes...${NC}"

# Frontend DNS route
echo -e "${YELLOW}Creating DNS route for ${FRONTEND_SUBDOMAIN}...${NC}"
if cloudflared tunnel route dns "$TUNNEL_NAME" "$FRONTEND_SUBDOMAIN" 2>&1 | grep -q "already exists\|Created CNAME"; then
    echo -e "${GREEN}✓ Frontend DNS route ready: ${FRONTEND_SUBDOMAIN}${NC}"
else
    echo -e "${RED}✗ Failed to create frontend DNS route${NC}"
fi

# API DNS route
echo -e "${YELLOW}Creating DNS route for ${API_SUBDOMAIN}...${NC}"
if cloudflared tunnel route dns "$TUNNEL_NAME" "$API_SUBDOMAIN" 2>&1 | grep -q "already exists\|Created CNAME"; then
    echo -e "${GREEN}✓ API DNS route ready: ${API_SUBDOMAIN}${NC}"
else
    echo -e "${RED}✗ Failed to create API DNS route${NC}"
fi
echo ""

# Step 4: Find the credentials file
echo -e "${BLUE}Step 4: Locating credentials file...${NC}"
CREDENTIALS_FILE="$HOME/.cloudflared/${TUNNEL_ID}.json"
if [ ! -f "$CREDENTIALS_FILE" ]; then
    echo -e "${RED}✗ Credentials file not found at: ${CREDENTIALS_FILE}${NC}"
    echo -e "${YELLOW}Searching for credentials files...${NC}"
    find "$HOME/.cloudflared" -name "*.json" -type f 2>/dev/null || true
    exit 1
fi
echo -e "${GREEN}✓ Found credentials: ${CREDENTIALS_FILE}${NC}"
echo ""

# Step 5: Create config file
echo -e "${BLUE}Step 5: Creating configuration file...${NC}"
CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/config.yml"

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
# UFC Pokedex Cloudflare Tunnel Configuration
# Generated by scripts/setup_tunnel.sh

tunnel: ${TUNNEL_ID}
credentials-file: ${CREDENTIALS_FILE}

ingress:
  # Frontend (Next.js)
  - hostname: ${FRONTEND_SUBDOMAIN}
    service: http://localhost:3000
    originRequest:
      noTLSVerify: true

  # API (FastAPI)
  - hostname: ${API_SUBDOMAIN}
    service: http://localhost:8000
    originRequest:
      noTLSVerify: true

  # Catch-all rule (required)
  - service: http_status:404
EOF

echo -e "${GREEN}✓ Config file created at: ${CONFIG_FILE}${NC}"
echo ""

# Step 6: Validate configuration
echo -e "${BLUE}Step 6: Validating tunnel configuration...${NC}"
if cloudflared tunnel ingress validate 2>&1; then
    echo -e "${GREEN}✓ Configuration is valid${NC}"
else
    echo -e "${RED}✗ Configuration validation failed${NC}"
    exit 1
fi
echo ""

# Summary
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                    Setup Complete! ✓                       ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Your tunnel is configured with:${NC}"
echo -e "  ${YELLOW}Tunnel Name:${NC} ${TUNNEL_NAME}"
echo -e "  ${YELLOW}Tunnel ID:${NC}   ${TUNNEL_ID}"
echo ""
echo -e "${BLUE}Your public URLs will be:${NC}"
echo -e "  ${YELLOW}Frontend:${NC} https://${FRONTEND_SUBDOMAIN}"
echo -e "  ${YELLOW}Backend:${NC}  https://${API_SUBDOMAIN}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo -e "  1. Update your ${YELLOW}.env${NC} file with the tunnel URLs"
echo -e "  2. Run ${YELLOW}make dev${NC} to start all services with tunnels"
echo ""
echo -e "${GREEN}The tunnel will automatically start when you run 'make dev'${NC}"
echo ""
